#!/usr/bin/env python
import sys
import subprocess
import json

CONFIG="config.json"

def main():
  args = sys.argv
  if len(args) >= 3:
    args.pop(0)
    name, command, *_ = args
    with open(CONFIG) as f:
      config = json.load(f)
      vm = config.get(name, {})
      commands = vm.get(command, [])
      for c in commands:
        subprocess.run(c)

if __name__ == "__main__":
  main()
